/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NetBeans;

import java.awt.event.ActionListener;

/**
 *
 * @author Vicha Octavia Tama
 */
public class HomeTimeline extends javax.swing.JFrame {

    /**
     * Creates new form HomeTimeline
     */
    public HomeTimeline() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txAreaTimeline = new javax.swing.JTextField();
        BtnCompose = new javax.swing.JButton();
        BtnFollowUser = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCompose.setText("Compose");

        BtnFollowUser.setText("Follow User");

        BtnRefresh.setText("Refresh");

        BtnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txAreaTimeline)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCompose)
                        .addGap(18, 18, 18)
                        .addComponent(BtnFollowUser)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txAreaTimeline, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCompose)
                    .addComponent(BtnFollowUser)
                    .addComponent(BtnRefresh)
                    .addComponent(BtnExit))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCompose;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnFollowUser;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField txAreaTimeline;
    // End of variables declaration//GEN-END:variables

    public void addListener(ActionListener e) {
        BtnCompose.addActionListener(e);
        BtnExit.addActionListener(e);
        BtnFollowUser.addActionListener(e);
        BtnRefresh.addActionListener(e);
    }
    public Object getBtnCompose(){
        return BtnCompose;
    }
    public Object getBtnExit(){
        return BtnExit;
    }
    public Object getBtnFollow(){
        return BtnFollowUser;
    }
    public Object getBtnRefresh(){
        return BtnRefresh;
    }
    public void setTimeline(String s){
        txAreaTimeline.setText(s);
    }
}

